import './bootstrap';
import htmx from 'htmx.org';
import {
    createIcons,
    AlertCircle,
    AlertTriangle,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    Bot,
    Calendar,
    CalendarX2,
    Check,
    CheckCircle,
    CheckCircle2,
    ChevronDown,
    ChevronRight,
    ChevronsUpDown,
    Clock,
    Compass,
    Download,
    Drama,
    ExternalLink,
    Eye,
    EyeOff,
    Film,
    Filter,
    Globe,
    Heart,
    History,
    Home,
    Image,
    Inbox,
    Info,
    Key,
    Languages,
    LayoutGrid,
    Link,
    Loader2,
    Lock,
    LogIn,
    LogOut,
    Mail,
    Map,
    MapPin,
    Menu,
    Music,
    Palette,
    Phone,
    RefreshCw,
    RotateCcw,
    Search,
    Share2,
    Shield,
    ShieldAlert,
    ShieldCheck,
    SlidersHorizontal,
    Smile,
    Sparkles,
    Star,
    Table2,
    Tag,
    Theater,
    Ticket,
    Trash2,
    Upload,
    User,
    UserCheck,
    UserPlus,
    Users,
    Wrench,
    X,
    Activity,
    BookOpen
} from 'lucide';
import flatpickr from 'flatpickr';
import { Latvian } from 'flatpickr/dist/l10n/lv.js';
import { Russian } from 'flatpickr/dist/l10n/ru.js';
import 'flatpickr/dist/flatpickr.min.css';

// Active Lucide icons map for tree-shaking
const appIcons = {
    AlertCircle,
    AlertTriangle,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    Bot,
    Calendar,
    CalendarX2,
    Check,
    CheckCircle,
    CheckCircle2,
    ChevronDown,
    ChevronRight,
    ChevronsUpDown,
    Clock,
    Compass,
    Download,
    Drama,
    ExternalLink,
    Eye,
    EyeOff,
    Film,
    Filter,
    Globe,
    Heart,
    History,
    Home,
    Image,
    Inbox,
    Info,
    Key,
    Languages,
    LayoutGrid,
    Link,
    Loader2,
    Lock,
    LogIn,
    LogOut,
    Mail,
    Map,
    MapPin,
    Menu,
    Music,
    Palette,
    Phone,
    RefreshCw,
    RotateCcw,
    Search,
    Share2,
    Shield,
    ShieldAlert,
    ShieldCheck,
    SlidersHorizontal,
    Smile,
    Sparkles,
    Star,
    Table2,
    Tag,
    Theater,
    Ticket,
    Trash2,
    Upload,
    User,
    UserCheck,
    UserPlus,
    Users,
    Wrench,
    X,
    Activity,
    BookOpen
};

window.htmx = htmx;
window.flatpickr = flatpickr;
window.flatpickrLocales = {
    'lv': Latvian,
    'ru': Russian,
    'en': 'default'
};

// Dispatch event notifying that flatpickr is ready
window.dispatchEvent(new CustomEvent('flatpickr-ready'));
document.dispatchEvent(new CustomEvent('flatpickr-ready'));

function renderIcons() {
    createIcons({ icons: appIcons });
}

// Initialize Lucide icons on page load and on every HTMX content swap
document.addEventListener('DOMContentLoaded', renderIcons);
document.addEventListener('htmx:afterSwap', renderIcons);
document.addEventListener('htmx:afterSettle', renderIcons);

